
fixtures:
  symlinks:
    netbox: "#{source_dir}"
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      tag:  '4.6.0'
    archive:
      repo: 'https://github.com/voxpupuli/puppet-archive.git'
      tag: '1.0.0'
    nginx:
      repo: 'https://github.com/voxpupuli/puppet-nginx.git'
      tag: 'v0.6.0'
    python:
      repo: 'https://github.com/stankevich/puppet-python.git'
      tag: '1.14.0'
